const mongoose=require("mongoose")

const schema=new mongoose.Schema({
    title:{
        type:String,
        require:true
    },
    userName:{
        type:String,
        require:true
    },
    status:{
        type:String,
       default:"yet to submit",
       enum:[
        "yet to submit",
        "scheduled",
        "In-progress",
        "assestment completed",
        "Yet to schedule Assign",
        "In-review",
        "Approve",
        "Rejected"
       ]
    },
    score:{
    type:String,
    },
    type:{
        type:String,
        default:"External",
        enum:[
            "Internal",
            "External"
        ]
    },
    to:{
        type:Date,
        require:true
    },
    from:{
       type:Date,
       require:true
    },
    schedule:{
    type:Boolean,
    default:false
    },
    Status:{
        type:String,
        default:"Active"
    },
    uniQ_Id:{
        type:String,
    },

    doc1:{
        type:String,
        require:true
    },
    status1:{
        type:String,
        require:true
    },
    comment1:{
        type:String,
        require:true
    },
    doc2:{
        type:String,
        require:true
    },
    status2:{
        type:String,
        require:true
    },
    comment2:{
        type:String,
        require:true
    },
    doc3:{
        type:String,
        require:true
    },
    status3:{
        type:String,
        require:true
    },
    comment3:{
        type:String,
        require:true
    },
    doc4:{
        type:String,
        require:true
    },
    status4:{
        type:String,
        require:true
    },
    comment4:{
        type:String,
        require:true
    },
    doc5:{
        type:String,
        require:true
    },
    status5:{
        type:String,
        require:true
    },
    comment5:{
        type:String,
        require:true
    },
    doc6:{
        type:String,
        require:true
    },
    status6:{
        type:String,
        require:true
    },
    comment6:{
        type:String,
        require:true
    },
    doc7:{
        type:String,
        require:true
    },
    status7:{
        type:String,
        require:true
    },
    comment7:{
        type:String,
        require:true
    },
    qdoc1:{
        type:String,
        require:true
    },
    qstatus1:{
        type:String,
        require:true
    },
    qcomment1:{
        type:String,
        require:true
    },
    qdoc2:{
        type:String,
        require:true
    },
    qstatus2:{
        type:String,
        require:true
    },
    qcomment2:{
        type:String,
        require:true
    },
    qdoc3:{
        type:String,
        require:true
    },
    qstatus3:{
        type:String,
        require:true
    },
    qcomment3:{
        type:String,
        require:true
    },
    qdoc4:{
        type:String,
        require:true
    },
    qstatus4:{
        type:String,
        require:true
    },
    qcomment4:{
        type:String,
        require:true
    },
   qdoc5:{
        type:String,
        require:true
    },
    qstatus5:{
        type:String,
        require:true
    },
    qcomment5:{
        type:String,
        require:true
    },
    qdoc6:{
        type:String,
        require:true
    },
    qstatus6:{
        type:String,
        require:true
    },
    qcomment6:{
        type:String,
        require:true
    },
    qdoc7:{
        type:String,
        require:true
    },
    qstatus7:{
        type:String,
        require:true
    },
    qcomment7:{
        type:String,
        require:true
    },
    // adge_Id:{
    //     type:mongoose.Schema.Types.ObjectId,
    //     ref:"adgePanel"
    // },
    Score:{
        type:Array,
    },
    scoreTwo:{
    type:Array
    },
    totalGover:{
        type:String
    },
    totalQuatily:{
        type:String
    },
    totalScore:{
        type:String
    },
    accept1:{
        type:String,
    },
    accept2:{
        type:String,
    },
    accept3:{
        type:String,
    },
    accept4:{
        type:String,
    },
    accept5:{
        type:String,
    },
    accept6:{
        type:String,
    },
    accept7:{
        type:String,
    },
    qaccept1:{
        type:String,
    },
    qaccept2:{
        type:String,
    },
    qaccept3:{
        type:String,
    },
    qaccept4:{
        type:String,
    },
    qaccept5:{
        type:String,
    },
    qaccept6:{
        type:String,
    },
    qaccept7:{
        type:String,
    },

})
schema.set("timestamps",true)
module.exports=mongoose.model("adgePanel",schema)