const mongoose=require("mongoose")

const schema=new mongoose.Schema({
    title:{
        type:String,
        require:true
    },
    userName:{
        type:String,
        require:true
    },
    status:{
        type:String,
       default:"yet to submit",
       enum:[
        "yet to submit",
        "scheduled",
        "In-progress",
        "assestment completed",
        "Yet to schedule Assign",
        "In-review",
        "Approve",
        "Rejected"
       ]
    },
    score:{
    type:String,
    },
    type:{
        type:String,
        default:"External",
        enum:[
            "Internal",
            "External"
        ]
    },
    to:{
        type:Date,
        require:true
    },
    from:{
       type:Date,
       require:true
    },
    schedule:{
    type:Boolean,
    default:false
    },
    Status:{
        type:String,
        default:"Active"
    },
    uniQ_Id:{
        type:String,
    },
    accept1:{
        type:String,
    },
    accept2:{
        type:String,
    },
    accept3:{
        type:String,
    },
    accept4:{
        type:String,
    },
    accept5:{
        type:String,
    },
    accept6:{
        type:String,
    },
    accept7:{
        type:String,
    },
    qaccept1:{
        type:String,
    },
    qaccept2:{
        type:String,
    },
    qaccept3:{
        type:String,
    },
    qaccept4:{
        type:String,
    },
    qaccept5:{
        type:String,
    },
    qaccept6:{
        type:String,
    },
    qaccept7:{
        type:String,
    },
})
schema.set("timestamps",true)
module.exports=mongoose.model("adgePanel",schema)